// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CustomScaffold.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\bradley chatha\Desktop\livestock-website\CustomScaffold\Templates\Controller.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class Controller : ControllerBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Database.Models;
using Website.Filters;
using Website.Services;
using User = Database.Models.User;

namespace Website.Controllers
{
	public class ");
            
            #line 22 "C:\Users\bradley chatha\Desktop\livestock-website\CustomScaffold\Templates\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("Controller : Controller\r\n    {\r\n        private readonly LivestockContext _contex" +
                    "t;\r\n\r\n        public ");
            
            #line 26 "C:\Users\bradley chatha\Desktop\livestock-website\CustomScaffold\Templates\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("Controller(LivestockContext context)\r\n        {\r\n            _context = context;\r" +
                    "\n        }\r\n\r\n        public async Task<IActionResult> Index()\r\n        {\r\n     " +
                    "       var livestockContext = _context.");
            
            #line 33 "C:\Users\bradley chatha\Desktop\livestock-website\CustomScaffold\Templates\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ContextGetterString));
            
            #line default
            #line hidden
            this.Write(@";
            return View(await livestockContext.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var val = await _context.");
            
            #line 44 "C:\Users\bradley chatha\Desktop\livestock-website\CustomScaffold\Templates\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ContextGetterString));
            
            #line default
            #line hidden
            this.Write(".FirstOrDefaultAsync(m => m.");
            
            #line 44 "C:\Users\bradley chatha\Desktop\livestock-website\CustomScaffold\Templates\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityIdName));
            
            #line default
            #line hidden
            this.Write(" == id);\r\n            if (val == null)\r\n            {\r\n                return Not" +
                    "Found();\r\n            }\r\n\r\n            return View(val);\r\n        }\r\n\r\n\t\t[AimAut" +
                    "horize]\r\n        public IActionResult Create()\r\n        {\r\n            ");
            
            #line 56 "C:\Users\bradley chatha\Desktop\livestock-website\CustomScaffold\Templates\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ForeignKeyDropDownCreationString));
            
            #line default
            #line hidden
            this.Write("\r\n            return View();\r\n        }\r\n\r\n        [HttpPost]\r\n        [ValidateA" +
                    "ntiForgeryToken]\r\n\t\t[AimAuthorize]\r\n        public async Task<IActionResult> Cre" +
                    "ate([Bind(\"");
            
            #line 63 "C:\Users\bradley chatha\Desktop\livestock-website\CustomScaffold\Templates\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FormBindingParams));
            
            #line default
            #line hidden
            this.Write("\")]");
            
            #line 63 "C:\Users\bradley chatha\Desktop\livestock-website\CustomScaffold\Templates\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write(@" val)
        {
			this.FixNullFields(val);
            if (ModelState.IsValid)
            {
                _context.Add(val);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ");
            
            #line 72 "C:\Users\bradley chatha\Desktop\livestock-website\CustomScaffold\Templates\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ForeignKeyDropDownCreationWithSelectedIndexString));
            
            #line default
            #line hidden
            this.Write(@"
            return View(val);
        }

		[AimAuthorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var val = await _context.");
            
            #line 84 "C:\Users\bradley chatha\Desktop\livestock-website\CustomScaffold\Templates\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write(".FindAsync(id);\r\n            if (val == null)\r\n            {\r\n                ret" +
                    "urn NotFound();\r\n            }\r\n            ");
            
            #line 89 "C:\Users\bradley chatha\Desktop\livestock-website\CustomScaffold\Templates\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ForeignKeyDropDownCreationWithSelectedIndexString));
            
            #line default
            #line hidden
            this.Write("\r\n            return View(val);\r\n        }\r\n\r\n        [HttpPost]\r\n        [Valida" +
                    "teAntiForgeryToken]\r\n\t\t[AimAuthorize]\r\n        public async Task<IActionResult> " +
                    "Edit(int id, [Bind(\"");
            
            #line 96 "C:\Users\bradley chatha\Desktop\livestock-website\CustomScaffold\Templates\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FormBindingParams));
            
            #line default
            #line hidden
            this.Write("\")]");
            
            #line 96 "C:\Users\bradley chatha\Desktop\livestock-website\CustomScaffold\Templates\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write(" val)\r\n        {\r\n\t\t\tif(val.");
            
            #line 98 "C:\Users\bradley chatha\Desktop\livestock-website\CustomScaffold\Templates\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityIdName));
            
            #line default
            #line hidden
            this.Write(@" != id)
				return NotFound();

			this.FixNullFields(val);

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(val);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Exists(val.");
            
            #line 112 "C:\Users\bradley chatha\Desktop\livestock-website\CustomScaffold\Templates\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityIdName));
            
            #line default
            #line hidden
            this.Write(@"))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ");
            
            #line 123 "C:\Users\bradley chatha\Desktop\livestock-website\CustomScaffold\Templates\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ForeignKeyDropDownCreationWithSelectedIndexString));
            
            #line default
            #line hidden
            this.Write(@"
            return View(val);
        }

		[AimAuthorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var val = await _context.");
            
            #line 135 "C:\Users\bradley chatha\Desktop\livestock-website\CustomScaffold\Templates\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ContextGetterString));
            
            #line default
            #line hidden
            this.Write(".FirstOrDefaultAsync(m => m.");
            
            #line 135 "C:\Users\bradley chatha\Desktop\livestock-website\CustomScaffold\Templates\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityIdName));
            
            #line default
            #line hidden
            this.Write(@" == id);
            if (val == null)
            {
                return NotFound();
            }

            return View(val);
        }

        [HttpPost, ActionName(""Delete"")]
        [ValidateAntiForgeryToken]
		[AimAuthorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var val = await _context.");
            
            #line 149 "C:\Users\bradley chatha\Desktop\livestock-website\CustomScaffold\Templates\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write(".FindAsync(id);\r\n            _context.");
            
            #line 150 "C:\Users\bradley chatha\Desktop\livestock-website\CustomScaffold\Templates\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write(".Remove(val);\r\n            await _context.SaveChangesAsync();\r\n            return" +
                    " RedirectToAction(nameof(Index));\r\n        }\r\n\r\n\t\tprivate void FixNullFields(");
            
            #line 155 "C:\Users\bradley chatha\Desktop\livestock-website\CustomScaffold\Templates\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write(" val)\r\n\t\t{\r\n\t\t\t");
            
            #line 157 "C:\Users\bradley chatha\Desktop\livestock-website\CustomScaffold\Templates\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FixNullFieldsCode));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t}\r\n\r\n        private bool Exists(int id)\r\n        {\r\n            return _cont" +
                    "ext.");
            
            #line 162 "C:\Users\bradley chatha\Desktop\livestock-website\CustomScaffold\Templates\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write(".Any(e => e.");
            
            #line 162 "C:\Users\bradley chatha\Desktop\livestock-website\CustomScaffold\Templates\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityIdName));
            
            #line default
            #line hidden
            this.Write(" == id);\r\n        }\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class ControllerBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
